name: "build-all-templates"

on:
  workflow_dispatch:
  
jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
    - name: "[preparation] checkout the current branch"
      uses: actions/checkout@v3.5.3
