name: GitHub Actions Scheduled Tasks Demo
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Schduled task
        run: echo "This is a scheduled task"