name: GitHub Actions Scheduled Tasks Demo
on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Schduled task
        run: echo "This is a scheduled task"